### ISSUE TITLE
Assassin's Creed 3 (Remastered) crashes after changing the font

### ISSUE THREAD

**Issue by rm-NoobInCoding** [eprilx/FFDConverter#5]
I am trying to change the font of Assassin's Creed 3. At first, I changed the font texture file and the game ran without problems (of course, because the Fire_Font file was not changed, the fonts were not displayed correctly, but the game running without problems shows that the new texture is correct)
After changing the texture, I edited the Fire Font file using the tool and ran the game. But the game doesn't show any text at the beginning (when it says to press a key) and crashes after entering the main menu.

I am attaching the font I use for example
[Font.zip](https://github.com/eprilx/FFDConverter/files/12332937/Font.zip)

**Comment by eprilx** [comment]
The original fnt (ffd->fnt) has char id 9 and 10, but your Bakh.fnt doesn't.
Also try using the new [config.xml](https://github.com/eprilx/FFDConverter/blob/master/FFDConverter/config.xml) which is not include in 1.3.2 version because I don't have time to make a newer release. Download and replace old config.xml.
